---
title: "Interactive_Counts_2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
library(gganimate)
library(transformr)
library(ggplot2)
library(gifski)
library(plotly)
theme_set(theme_bw())
```


## Total CFU from All Tanks Tested 2/27/2020 to 11/12/2020
```{r, fig.width = 10, fig.height = 6, echo=FALSE}
plate_counts_df_11_12 <- read_csv("2017_plate_counts_fixed_11_12.csv",
    col_types = cols(Dilution_X = col_number(), 
        Half_Plate_Count_TSA_W_SB = col_number(), 
        Full_Plate = col_number(), Hours = col_number(), 
        Count_X_Dil = col_number(), Total_CFU = col_number()),
    locale = locale())
view(plate_counts_df_11_12)

plate_counts_df_11_12 %>% 
  group_by(Date_Read, Tank, Total_CFU) %>% 
  filter(Date_Read >= as.Date("2020-02-27")) %>% 
  ggplot(aes(x = Date_Read, y = Total_CFU)) +
  geom_point((aes(color = Tank))) +
    geom_line((aes(color = Tank))) +
    ggtitle("2020 Plate Counts Per Tank")
```

# 2020 Plate Counts per Tank Since 4/27/2020
```{r, fig.width = 10, fig.height = 6, echo=FALSE}
plate_counts_df_11_12 <- read_csv("2017_plate_counts_fixed_11_12.csv",
    col_types = cols(Dilution_X = col_number(), 
        Half_Plate_Count_TSA_W_SB = col_number(), 
        Full_Plate = col_number(), Hours = col_number(), 
        Count_X_Dil = col_number(), Total_CFU = col_number()),
    locale = locale())

plate_counts_df_11_12 %>% 
  group_by(Date_Read, Tank, Total_CFU) %>% 
  filter(Date_Read >= as.Date("2020-04-27")) %>% 
  ggplot(aes(x = Date_Read, y = Total_CFU)) +
  geom_point((aes(color = Tank))) +
    geom_line((aes(color = Tank))) +
    ggtitle("2020 Plate Counts Per Tank")
```

## Interactive 2020 Plate Counts per Tank Since 4/27/2020
```{r, fig.width = 10, fig.height = 7, echo=FALSE}
ggplotly(
  plate_counts_df_11_12 %>% 
  group_by(Date_Read, Tank, Total_CFU) %>% 
  filter(Date_Read >= as.Date("2020-02-27")) %>% 
  filter(Tank %in% c("A High", "B High", "B6", "C High", "D High", "E High", "HT", "P1 High", "P2 High", "P6 High", "P7 High", "P9 High", "P9", "P10", "P10 High")) %>% 
  ggplot(aes(x = Date_Read, y = Total_CFU)) +
  geom_point((aes(color = Tank))) +
  geom_line((aes(color = Tank))) +
  ggtitle("Total CFU per Tank Since 2/7/2020") +
  geom_point(aes(color = Tank))
)
```

# A System -> A High
```{r, echo=FALSE}
p <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("A High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "Red")) +
      ggtitle("Total CFU in A System Since 2/27/2020"))
hide_legend(p)
```

# B System -> B High
```{r, echo=FALSE}
q <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("B High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "chocolate1")) +
      ggtitle("Total CFU in B System Since 2/27/2020"))
hide_legend(q)
```

# C System -> C High
```{r, echo=FALSE}
r <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("C High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "darkgoldenrod1")) +
      ggtitle("Total CFU in C System Since 2/27/2020"))
hide_legend(r)
```

# D System -> D High
```{r, echo=FALSE}
s <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("D High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in D System Since 2/27/2020"))
hide_legend(s)
```

# E System -> E High
```{r, echo=FALSE}
t <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("E High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in E System Since 2/27/2020"))
hide_legend(t)
```

# F System -> F High
```{r, echo=FALSE}
t <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("F High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in F System Since 2/27/2020"))
hide_legend(t)
```


# P1 System -> P1 High
```{r, echo=FALSE}
l <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("P1 High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in P1 Since 2/27/2020"))
hide_legend(l)
```

# P2 System -> P2 High
```{r, echo=FALSE}
m <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("P2 High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in P2 Since 2/27/2020"))
hide_legend(m)
```

# P6 System -> P6 High
```{r, echo=FALSE}
n <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("P6 High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in P6 Since 2/27/2020"))
hide_legend(n)
```

# P7 System -> P7 High
```{r, echo=FALSE}
o <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("P7 High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in P7 Since 1/1/2020"))
hide_legend(o)
```

# P9 System -> P9 High
```{r, echo=FALSE}
u <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("P9 High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU in P6 Since 1/1/2020"))
hide_legend(u)
```

# P10 System -> P10 High
```{r, echo=FALSE}
v <- ggplotly(
  plate_counts_df_11_12 %>% 
    group_by(Date_Read, Tank, Total_CFU) %>% 
    filter(Date_Read >= as.Date("2020-01-01")) %>%
    filter(Tank %in% c("P10 High")) %>%
    ggplot(aes(x = Date_Read,  y = Total_CFU)) + 
      geom_point() +
      geom_line(aes(color = "red")) +
      ggtitle("Total CFU per Tank Since 1/1/2020"))
hide_legend(v)
```

# Holding Tank -> HT and HT GN Post-UV
```{r, echo=FALSE}
ggplotly(
  plate_counts_df_11_12 %>% 
  group_by(Date_Read, Tank, Total_CFU) %>% 
  filter(Date_Read >= as.Date("2020-01-01")) %>%
  filter(Tank %in% c("HT", "HTGN Post-UV")) %>%
  ggplot(aes(x = Date_Read, y = Total_CFU)) +
  geom_point((aes(color = Tank))) +
    geom_line((aes(color = Tank, group = Tank))) +
    ggtitle("Total CFU in the HT Since 1/1/2020") +
  labs(x = "Date", y = "Total_Colony_Forming_Units") +
  theme_light() +
  theme(text = element_text (size = 12)))
```
